"""
Inspector Python API acquisition script for the Falcon (FN-DSA) firmware
running on Pinata.

Current phase: profile coefficient f[0] alone first (63 possible values),
before attempting the full 512-coefficient joint recovery. Point this at
a SWEEP key set (below), not a batch of independent random keys - a sweep
varies only f[0] and holds one base key's g, F, and public key fixed
across all 63 records, which is what makes it a clean single-variable
experiment (see Pinata/BUILDING_ON_WINDOWS.md for the reasoning and a
from-scratch verification of that claim on real bytes).

Requirements:
  - Inspector must already be running before you start this script (it
    connects to that running instance via riscure.inspector.connect()).
  - A key set generated by Pinata/tools/host_keygen, e.g. for the f[0]
    sweep (current phase):
        cmake -S Pinata/tools/host_keygen -B Pinata/tools/host_keygen/build
        cmake --build Pinata/tools/host_keygen/build
        Pinata/tools/host_keygen/build/host_keygen sweep 0 falcon_sweep
    which writes falcon_sweep.bin + falcon_sweep.meta.json (63 records:
    one base key, f[0] swept over all its valid values, everything else
    held fixed). Point the "Key set file prefix" parameter at that
    prefix (default: "falcon_sweep" in the working directory this script
    is run from). For a later full-key attack, `host_keygen <N> <prefix>`
    (no "sweep") generates N independent random keys instead.
"""

import contextlib
import json
import math
import os
import sys
import warnings
from time import perf_counter_ns
from types import TracebackType
from typing import Any, Iterator, List, Optional, Type, Tuple, Iterable, MutableMapping, Union, cast

import serial

import riscure.inspector
from riscure.inspector import (
    Inspector,
    JavaError,
    ScopeDevice,
    ManualInputTraceSetSink,
    ManualInputJob,
    StringParameter,
    SelectionParameter,
    ConstantIntParameter,
    ConstantFloatParameter,
    ParameterConfig,
    ScopeSource,
)
from riscure.inspector.util import restore_parameter_cache, save_parameter_cache

trs_filename = "Result file name"
target_port = "Serial target port"
scope_param = "Oscilloscope"
num_measurements = "Total number of measurements"
key_set_prefix_param = "Key set file prefix"
traces_per_key_param = "Traces per key (profiling)"


class FalconKeySet:
    """
    A batch of real, valid FN-DSA-512 keypairs plus their decoded f/g
    ground truth, as produced by Pinata/tools/host_keygen (main.c there
    documents the exact binary layout). Loading is driven entirely by the
    .meta.json sidecar so this loader never hardcodes offsets that could
    drift out of sync with that tool.
    """

    def __init__(self, pk: List[bytes], sk: List[bytes], f: List[bytes], g: List[bytes]) -> None:
        if not pk or not (len(pk) == len(sk) == len(f) == len(g)):
            raise ValueError("key set is empty or internally inconsistent")
        self.pk = pk
        self.sk = sk
        self.f = f
        self.g = g

    def __len__(self) -> int:
        return len(self.pk)

    @classmethod
    def load(cls, prefix: str) -> "FalconKeySet":
        meta_path = prefix + ".meta.json"
        bin_path = prefix + ".bin"
        with open(meta_path, "r") as fh:
            meta = json.load(fh)
        record_size = meta["record_size"]
        num_keys = meta["num_keys"]
        fields = meta["fields"]
        with open(bin_path, "rb") as fh:
            data = fh.read()
        if len(data) != record_size * num_keys:
            raise ValueError(
                f"{bin_path} is {len(data)} bytes, but {meta_path} claims "
                f"{num_keys} x {record_size}-byte records - regenerate both together."
            )
        pk: List[bytes] = []
        sk: List[bytes] = []
        f: List[bytes] = []
        g: List[bytes] = []
        for i in range(num_keys):
            base = i * record_size

            def field(name: str) -> bytes:
                spec = fields[name]
                start = base + spec["offset"]
                return data[start:start + spec["size"]]

            pk.append(field("pk"))
            sk.append(field("sk"))
            f.append(field("f"))
            g.append(field("g"))
        return cls(pk, sk, f, g)


class FalconPinataClient:
    """
    A client connection to a Pinata device running the Falcon (FN-DSA)
    firmware. See Pinata/src/main.h (CMD_SW_FALCON_*) and
    Pinata/src/falcon/wrapper.h for the sizes/opcodes this mirrors.
    """

    __REQUEST_SET_KEY: bytes = b"\x9B"
    __REQUEST_SIGN: bytes = b"\x9C"
    PUBLIC_KEY_SIZE: int = 897
    PRIVATE_KEY_SIZE: int = 1281
    SIGNATURE_SIZE: int = 666
    MESSAGE_SIZE: int = 16

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self.__serial = serial.Serial(*args, **kwargs)

    def __enter__(self) -> "FalconPinataClient":
        return self

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> None:
        self.__serial.close()

    def reset_input_buffer(self) -> None:
        self.__serial.reset_input_buffer()

    def reset_output_buffer(self) -> None:
        self.__serial.reset_output_buffer()

    def reset_buffers(self) -> None:
        self.reset_input_buffer()
        self.reset_output_buffer()

    def set_public_private_key(self, public_key: bytes, private_key: bytes) -> None:
        """
        Load a keypair onto the device. Must be called once before signing.
        """
        if len(public_key) != self.PUBLIC_KEY_SIZE or len(private_key) != self.PRIVATE_KEY_SIZE:
            raise ValueError("public/private key have the wrong size")
        self.__serial.write(self.__REQUEST_SET_KEY + public_key + private_key)
        status = self.__serial.read(1)
        if len(status) != 1 or status[0] != 0:
            raise RuntimeError(f"failed to set Falcon keypair on Pinata (status={status!r})")

    def sign(self, message: bytes) -> bytes:
        """
        Sign a 16-byte message. This is the traced operation: the firmware
        toggles GPIO PC2 tightly around decoding the 'f' coefficient of the
        secret key (see patches/fndsa-sign.patch), before doing the rest of
        the (untraced) signing computation.
        """
        if len(message) != self.MESSAGE_SIZE:
            raise ValueError(f"message must be exactly {self.MESSAGE_SIZE} bytes")
        self.__serial.write(self.__REQUEST_SIGN + message)
        status = self.__serial.read(1)
        if len(status) != 1 or status[0] != 0:
            raise RuntimeError(f"Falcon sign failed on Pinata (status={status!r})")
        signature = self.__serial.read(self.SIGNATURE_SIZE)
        if len(signature) != self.SIGNATURE_SIZE:
            raise RuntimeError(
                f"short read for signature (expected {self.SIGNATURE_SIZE} bytes, got {len(signature)})"
            )
        return signature


def filter_valid_keys(target: FalconPinataClient, keyset: FalconKeySet) -> FalconKeySet:
    """
    Probe every key in the set with one throwaway sign before starting the
    real (timed) acquisition, and keep only the ones the device actually
    accepts.

    sign_step1() (see patches/fndsa-sign.patch / ref/sign.c) rejects a key
    purely based on its own bytes - before any message is touched - if f/g/F
    fail to decode, f isn't invertible mod q, or the recomputed G falls
    outside the valid coefficient range. A sweep key set (host_keygen sweep)
    deliberately walks one coefficient through every representable value, so
    some variants are expected to be mathematically invalid keys; letting
    that surface here (once, up front) is much cheaper than crashing mid-run
    on trace 8000+.
    """
    probe_message = b"KeyProbeMessage!"  # exactly 16 bytes
    assert len(probe_message) == FalconPinataClient.MESSAGE_SIZE

    good_idx: List[int] = []
    for i in range(len(keyset)):
        target.set_public_private_key(keyset.pk[i], keyset.sk[i])
        try:
            target.sign(probe_message)
            good_idx.append(i)
        except RuntimeError:
            print(f"  key {i}: REJECTED by device (invalid key material) - excluding from sweep")

    if len(good_idx) == len(keyset):
        print(f"  all {len(keyset)} keys accepted")
        return keyset
    if not good_idx:
        raise RuntimeError("no key in the set was accepted by the device - nothing to measure")

    print(f"  {len(good_idx)}/{len(keyset)} keys accepted, {len(keyset) - len(good_idx)} excluded")
    return FalconKeySet(
        pk=[keyset.pk[i] for i in good_idx],
        sk=[keyset.sk[i] for i in good_idx],
        f=[keyset.f[i] for i in good_idx],
        g=[keyset.g[i] for i in good_idx],
    )


@contextlib.contextmanager
def check_performance(token: str) -> Iterator:
    start_ns = perf_counter_ns()
    try:
        yield
    finally:
        print(f"{token} took {int((perf_counter_ns() - start_ns) / 1e6)}ms")


def setup_scope(ins: Inspector, scope: ScopeDevice) -> str:
    """
    Configure the oscilloscope's settings (channel, range, trigger on GPIO PC2).
    """
    num_samples = "Number of samples"
    sample_rate = "Sampling rate (MHz)"
    measurement_channel = "Measurement channel"
    measurement_range = "Measurement range (V)"
    trigger_channel = "Trigger channel"
    trigger_level = "Trigger level (V)"

    settings = scope.scope_settings
    data_channel_names = list(scope.data_channel_settings.keys())
    trigger_channel_names = list(scope.trigger_channel_settings.keys())
    default_measurement_range: Union[ConstantFloatParameter, SelectionParameter]
    default_trigger_level: Union[ConstantFloatParameter, SelectionParameter]

    if scope.channel_settings[data_channel_names[0]].is_freeform_range_supported:
        default_measurement_range = ConstantFloatParameter(ins, measurement_range, 0.2)
        default_trigger_level = ConstantFloatParameter(ins, trigger_level, 1.0)
    else:
        supported_ranges = scope.channel_settings[data_channel_names[0]].supported_ranges
        supported_ranges_str = list(map(str, supported_ranges))
        default_measurement_range = SelectionParameter(ins, measurement_range, supported_ranges_str)
        default_trigger_level = SelectionParameter(ins, trigger_level, supported_ranges_str)

    defaults = {
        num_samples: ConstantIntParameter(ins, num_samples, 125000),
        sample_rate: ConstantIntParameter(ins, sample_rate, 500),
        measurement_channel: SelectionParameter(ins, measurement_channel, data_channel_names),
        measurement_range: default_measurement_range,
        trigger_channel: SelectionParameter(ins, trigger_channel, trigger_channel_names),
        trigger_level: default_trigger_level,
    }
    print("Requesting user input for scope settings in Inspector dialog ... ", end="")

    scope_params = ins.parameter_configuration_dialog(defaults)
    if scope_params is None:
        print("CANCELLED\nStopping script: User input was not confirmed.")
        sys.exit(0)
    print("OK")
    print("Configuring scope ... ", end="")

    if scope_params[measurement_channel] is None:
        print("ERROR\nNo measurement channel selected")
        sys.exit(-1)
    if scope_params[trigger_channel] is None:
        print("ERROR\nNo trigger channel selected")
        sys.exit(-1)

    settings.sample_count = scope_params[num_samples]
    settings.time_per_sample = 1 / (scope_params[sample_rate] * 1_000_000)
    scope.channel_settings[scope_params[measurement_channel]].enabled = True
    scope.channel_settings[scope_params[measurement_channel]].range = float(scope_params[measurement_range])
    if scope_params[trigger_channel] != scope_params[measurement_channel]:
        scope.channel_settings[scope_params[trigger_channel]].enabled = False
    scope.trigger_settings.channel_name = scope_params[trigger_channel]
    scope.trigger_settings.level = float(scope_params[trigger_level])

    scope.calibrate()
    print("OK")
    return cast(str, scope_params[measurement_channel])


def connect_to_scope(
    ins: Inspector, connected_scopes: Iterable[MutableMapping[str, str]], selected_scope_name: str
) -> Tuple[ScopeDevice, str]:
    scope_descriptor = None
    for descriptor in connected_scopes:
        if descriptor["name"] == selected_scope_name:
            scope_descriptor = descriptor
    if scope_descriptor is not None:
        print(f"Opening connection to {scope_descriptor['name']} ... ", end="")
        try:
            scope = ins.open_scope_device(scope_descriptor)
            print("OK")
            if scope.scope_settings.is_headless:
                measurement_channel = scope.first_active_channel
            else:
                measurement_channel = setup_scope(ins, scope)
        except JavaError:
            print(
                "ERROR\nPlease make sure the scope is still connected, that it is not in use by something else, "
                "and that its settings are valid."
            )
            sys.exit(-1)
    else:
        print("Opening connection to oscilloscope ... ERROR\nNo oscilloscope was selected.")
        sys.exit(-1)
    return scope, measurement_channel


def do_measurements(
    target: FalconPinataClient,
    scope: ScopeDevice,
    parameters: ParameterConfig,
    source: ScopeSource,
    write_job: ManualInputJob,
    measurement_channel: str,
    keyset: FalconKeySet,
    traces_per_key: int,
) -> None:
    target.reset_buffers()
    total = parameters[num_measurements]
    iterations = (
        total
        if scope.scope_settings.batch_size == 0
        else math.floor(total / scope.scope_settings.batch_size)
    )
    if scope.scope_settings.batch_size and total % scope.scope_settings.batch_size:
        warnings.warn(
            f"Number of measurements: {total} is not a multiple of "
            f"batch size: {scope.scope_settings.batch_size}. The last "
            f"{total // scope.scope_settings.batch_size} attempt(s) will be discarded."
        )
    if iterations == 0:
        raise Exception(
            f"Number of measurements: {total} is lower than the "
            f"batch size={scope.scope_settings.batch_size}. The measurement is discarded."
        )

    keys_needed = math.ceil(total / traces_per_key)
    if len(keyset) < keys_needed:
        warnings.warn(
            f"Key set only has {len(keyset)} keys, but {total} measurements at "
            f"{traces_per_key} traces/key would ideally use {keys_needed} distinct keys. "
            f"Keys will repeat (cycled). Fine for a quick smoke test; for real profiling, "
            f"generate more keys with Pinata/tools/host_keygen so the model sees more "
            f"distinct known f/g values."
        )

    # Index into a fixed rotation of keys - trace i uses keyset[(i // traces_per_key) % len(keyset)].
    # current_key_index starts at -1 so the very first trace always sets a key on the device.
    trace_counter = 0
    current_key_index = -1

    def maybe_switch_key() -> Tuple[bytes, bytes, bytes, bytes]:
        nonlocal current_key_index
        key_index = (trace_counter // traces_per_key) % len(keyset)
        if key_index != current_key_index:
            target.set_public_private_key(keyset.pk[key_index], keyset.sk[key_index])
            current_key_index = key_index
        return keyset.pk[key_index], keyset.sk[key_index], keyset.f[key_index], keyset.g[key_index]

    for index in range(0, iterations):
        with check_performance(f"Iteration {index + 1}/{iterations}"):
            scope.arm()
            # case segmented mode
            if scope.scope_settings.batch_size != 0:
                messages = []
                signatures = []
                key_material = []
                for _ in range(scope.scope_settings.batch_size):
                    pk, sk, f, g = maybe_switch_key()
                    key_material.append((pk, sk, f, g))
                    messages.append(os.urandom(FalconPinataClient.MESSAGE_SIZE))
                    signatures.append(target.sign(messages[-1]))
                    trace_counter += 1
                with source.get() as measurement:
                    for i, trace in enumerate(measurement.get_traces(measurement_channel)):
                        pk, sk, f, g = key_material[i]
                        trace.parameters["MESSAGE"] = messages[i]
                        trace.parameters["SIGNATURE"] = signatures[i]
                        trace.parameters["PUBLIC_KEY"] = pk
                        trace.parameters["PRIVATE_KEY"] = sk
                        trace.parameters["F_COEFFS"] = f
                        trace.parameters["G_COEFFS"] = g
                        write_job.put(trace)
            # case non-segmented mode
            else:
                pk, sk, f, g = maybe_switch_key()
                message = os.urandom(FalconPinataClient.MESSAGE_SIZE)
                signature = target.sign(message)
                trace_counter += 1
                with source.get() as measurement:
                    for trace in measurement.get_traces(measurement_channel):
                        trace.parameters["MESSAGE"] = message
                        trace.parameters["SIGNATURE"] = signature
                        trace.parameters["PUBLIC_KEY"] = pk
                        trace.parameters["PRIVATE_KEY"] = sk
                        trace.parameters["F_COEFFS"] = f
                        trace.parameters["G_COEFFS"] = g
                        write_job.put(trace)


def main() -> None:
    print("Opening connection to Inspector ... ", end="")
    with riscure.inspector.connect() as ins:
        print("OK")
        print("Requesting user input in Inspector dialog ... ", end="")
        default_parameters = {
            trs_filename: StringParameter(ins, trs_filename, "SCA Falcon Pinata Acquisition.trs"),
            target_port: StringParameter(ins, target_port, "COM4"),
            scope_param: SelectionParameter(ins, scope_param, ["NO OPTIONS SET"]),
            # 63 f[0] values x 200 traces/value = 12600. Tune traces_per_key
            # once real trace noise is known; this is a starting point, not
            # a measured requirement.
            num_measurements: ConstantIntParameter(ins, num_measurements, 12600),
            key_set_prefix_param: StringParameter(ins, key_set_prefix_param, "falcon_sweep"),
            traces_per_key_param: ConstantIntParameter(ins, traces_per_key_param, 200),
        }
        connected_scopes = list(ins.get_connected_oscilloscopes())
        if connected_scopes:
            default_parameters[scope_param] = SelectionParameter(
                ins, scope_param, [descriptor["name"] for descriptor in connected_scopes]
            )

        parameters = ins.parameter_configuration_dialog(default_parameters, cache=restore_parameter_cache())
        if parameters.canceled:
            print("CANCELLED\nStopping script: User input was not confirmed.")
            return
        print("OK")

        print(f"Loading key set from {parameters[key_set_prefix_param]}.bin/.meta.json ... ", end="")
        try:
            keyset = FalconKeySet.load(parameters[key_set_prefix_param])
        except (OSError, ValueError, KeyError) as exc:
            print(
                f"ERROR\n{exc}\n"
                "Generate a key set first with Pinata/tools/host_keygen, e.g.:\n"
                "  cmake -S Pinata/tools/host_keygen -B Pinata/tools/host_keygen/build\n"
                "  cmake --build Pinata/tools/host_keygen/build\n"
                f"  Pinata/tools/host_keygen/build/host_keygen sweep 0 {parameters[key_set_prefix_param]}"
            )
            sys.exit(-1)
        print(f"OK ({len(keyset)} keys)")

        try:
            print(f"Opening serial connection to target on port {parameters[target_port]} ... ", end="")
            with FalconPinataClient(port=parameters[target_port], baudrate=115200, timeout=5.0) as pinata:
                print("OK")

                print(f"Pre-checking {len(keyset)} keys against the device (one throwaway sign each) ...")
                keyset = filter_valid_keys(pinata, keyset)

                (scope, measurement_channel) = connect_to_scope(ins, connected_scopes, parameters[scope_param])

                print("Creating sources... ", end="")
                source = ins.create_scope_source(scope)
                print("OK")

                # Keys are set per-trace inside do_measurements() (each trace is
                # tagged with the key that was active for it) rather than once
                # here, since a profiled attack needs many known keys, not one.
                source.trace_meta_data.trace_set_parameters["KEY_SET_PREFIX"] = parameters[key_set_prefix_param]
                source.trace_meta_data.trace_set_parameters["NUM_KEYS_AVAILABLE"] = len(keyset)
                source.trace_meta_data.trace_set_parameters["TRACES_PER_KEY"] = parameters[traces_per_key_param]

                file_name = os.path.join(ins.settings.trace_set_path, parameters[trs_filename])
                write_op = ManualInputTraceSetSink(ins, source.trace_meta_data, file_name)

                do_measurements(
                    target=pinata,
                    scope=scope,
                    parameters=parameters,
                    source=source,
                    write_job=write_op.run(),
                    measurement_channel=measurement_channel,
                    keyset=keyset,
                    traces_per_key=parameters[traces_per_key_param],
                )
        finally:
            save_parameter_cache(parameters)


if __name__ == "__main__":
    main()
